### PR TITLE
Add ECDH support to Python client

### PR DESCRIPTION
**Pull request by romanz**

### CODE REVIEW

**Comment by romanz** [comment]
This PR should have been submitted during https://github.com/trezor/trezor-mcu/issues/85 :)

**Comment by slush0** [comment]
Thanks for the PR, I'll watch trezor/trezor-mcu#85 and merge this.

**Comment by prusnak** [comment]
Thanks!

**Comment by prusnak** [comment]
Next time, please don't regenerate protobuf, just leave the information in the comment if that needs to be done. Thanks!

**Pull request merged**
