### PR TITLE
sign_tx: add rbf opt-in enable, add locktime, add tx version, sign based on path

### PR DESCRIPTION
**Pull request by mcudev**
i had this and figured i'd share it. it's simple and scratches some itches.
some other PRs might be going in a different direction, if so, please disregard.

### CODE REVIEW

**Comment by saleemrashid** [comment]
@mcudev Could you rebase it on #189 perhaps? I think that PR takes a better approach for script type detection

**Comment by mcudev** [comment]
@saleemrashid done please see the last commit here, thanks

**Comment by saleemrashid** [comment]
@mcudev The input amount is also required for coins that use BIP-143 and other possible future developments, so I would prefer to change that back.

**Comment by mcudev** [comment]
@saleemrashid makes sense, done

**Comment by prusnak** [comment]
Something weird happened here, rebased and merged in 49622077036c92def595800505e4b3940212b724

Please check that's correct.

**Comment by mcudev** [comment]
looks good, thanks!

**Pull request closed without merging**
