### PR TITLE
v2 protocol: bytearray for python2

### PR DESCRIPTION
**Pull request by mcudev**
Tested with `./trezorctl ping test` in bootloader and firmware modes of TREZORv2 using python2

### CODE REVIEW

**Comment by prusnak** [comment]
Actually hid_version means something different. It's not about v2 protocol. It's about the change when we decided to remove report_numbers from HID descriptor in the past and use messages without report ID. These messages are sent via byte sequence starting with an extra 0.

**Comment by mcudev** [comment]
ok, yeah i saw the `is_trezor1` and read right past that. still need the `bytearray` part for working with the v2 in non-bootloader mode.

**Comment by prusnak** [comment]
Closed via 54426761c62ac961c7742d51e95f0541b3a48edb

**Comment by mcudev** [comment]
thanks!

**Pull request closed without merging**
