### PR TITLE
Add libprotobuf2 support

### LINKED ISSUE #120: TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)
I am getting this error when my Trezor is connected when starting Electrum and when I try to perform a payment from Electrum.

All Fedora packages, trezor-python have protobuffer messages rebuilt with libprotoc 2.6.1
Electrum: 2.8.3
trezor-python: 0.7.16
protobuf-python: 2.6.1
Python 2.7.13

Stacktrace:
```
"sni-qt/11398" WARN  12:51:51.237 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/plugin.py", line 141, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 397, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 427, in force_pair_xpub
    client_xpub = client.get_xpub(derivation)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/clientbase.py", line 153, in get_xpub
    node = self.get_public_node(address_n, creating).node
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/clientbase.py", line 221, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/clientbase.py", line 198, in get_public_node
    return super(TrezorClientBase, self).get_public_node(address_n)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 521, in get_public_node
    return self.call(proto.GetPublicKey(address_n=n, ecdsa_curve_name=ecdsa_curve_name, show_display=show_display, coin_name=coin_name))
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 344, in init
    setattr(self, field_name, field_value)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
    self._fields[field] = type_checker.CheckValue(new_value)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 155, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)

```

### PR DESCRIPTION
**Pull request by saleemrashid**
[The check for `None` in message constructors](https://github.com/google/protobuf/blob/cf14183bcd5485b4a71541599ddce0b35eb71352/python/google/protobuf/internal/python_message.py#L500-L502) is not present in libprotobuf 2.6.1 and below and libprotobuf 2.7.0 was never released.

This pull request monkey patches the message constructors to remove `None` values.

Fixes #120

/cc @hegjon

### CODE REVIEW

**Comment by hegjon** [comment]
Just tested your patch, I got this stacktrace on Electrum startup with no Trezor connected:
```
Traceback (most recent call last):
  File "/usr/bin/electrum", line 379, in <module>
    d.init_gui(config, plugins)
  File "/usr/lib/python2.7/site-packages/electrum/daemon.py", line 282, in init_gui
    self.gui.main()
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 199, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 156, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "/usr/lib/python2.7/site-packages/electrum/daemon.py", line 219, in load_wallet
    wallet = Wallet(storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1756, in __new__
    wallet = WalletClass(storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1563, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1408, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 103, in __init__
    self.load_keystore()
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1530, in load_keystore
    self.keystore = load_keystore(self.storage, 'keystore')
  File "/usr/lib/python2.7/site-packages/electrum/keystore.py", line 617, in load_keystore
    k = hardware_keystore(d)
  File "/usr/lib/python2.7/site-packages/electrum/keystore.py", line 601, in hardware_keystore
    return constructor(d)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 169, in dynamic_constructor
    return self.get_plugin(name).keystore_class(d)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 177, in get_plugin
    self.load_plugin(name)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 102, in load_plugin
    plugin = p.Plugin(self, self.config, name)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/trezor.py", line 16, in __init__
    import client
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/client.py", line 1, in <module>
    from trezorlib.client import proto, BaseClient, ProtocolMixin
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 36, in <module>
    tools.monkeypatch_google_protobuf_addinitmethod()
  File "/usr/lib/python2.7/site-packages/trezorlib/tools.py", line 146, in monkeypatch_google_protobuf_addinitmethod
    if google.protobuf.__version__.startswith("2."):
AttributeError: 'module' object has no attribute '__version__'

```

**Comment by prusnak** [comment]
I confirm that upstream `protobuf==2.6.1` does not contain `google.protobuf.__version__`.

**Comment by prusnak** [comment]
Btw, I just noticed that new Fedora is going to be released tomorrow. Is this really worth fixing? I think most of the Fedora people are used to upgrading to new distros when it comes out and other distributions are shipping protobuf-3.x already (even Debian stable).

I am asking, because I would like to drop using of internally bundled protobuf_json and use the (de)serializer provided by protobuf-3.x, which will introduce even stronger dependency on protobuf-3.x.

(If you still want to fix, it probably makes sense to do in `0.7.x` branch, which I plan to keep for compatibility with Electrum et al., but I would like to do some more breaking changes in master).

**Comment by saleemrashid** [comment]
@hegjon Sorry about that, I don't have libprotobuf 2.6.1 installed on my system

**Comment by hegjon** [comment]
@prusnak 
I understand that you would like to move to protobuf3, it is easy for me to include the patch for the Fedora 25 package, so you do not need to include it in master.

Fedora 25 will be maintained until 1 month after the release of Fedora 27, so I need to maintain the package with security and bug fixes. Fedora 27 is probably released in the end of November 2017.

A 0.7.x branch would be great, then I can use that branch for Fedora 25, if not, then patches also works good.

**Comment by hegjon** [comment]
@saleemrashid no worries, thanks for providing new a patch. I will try it now.

**Comment by hegjon** [comment]
@saleemrashid I confirm that your patch works, I have signed and broadcasted a transaction with it in Electrum

**Comment by prusnak** [comment]
Cherry-picked this fix to 0.7.x branch. Also decreased requirement for protobuf to 2.6.1 in that branch. I am wondering whether we should regenerate *_pb2.py files using protobuf-2.6 to have 0.7.x completely 2.6.x compatible.

**Comment by hegjon** [comment]
I regenerated the *_pb2.py files for Fedora 25 for the RPM, then I am sure that it should work

**Comment by hegjon** [comment]
Here is how it is built for Fedora: http://pkgs.fedoraproject.org/cgit/rpms/python-trezor.git/tree/

```
%if %{protobuf2}
%patch0 -p0
%patch1 -p1
%endif
```

**Comment by prusnak** [comment]
Do you think it is a good idea to apply `protobuf2-messages-regenerated.patch` to 0.7.x branch? (the other patch is already applied in this branch, see https://github.com/trezor/python-trezor/commit/3806e51e5d5774290f215b366b5cce0af292248b).

Also do you think I should change requirement in 0.7.x branch to `protobuf==2.6.1`? So this branch will be only usable using protobuf-2.6.x and master would be usable only with protobuf-3.x?

**Comment by hegjon** [comment]
I think both suggestions sounds good, the protobuf2-messages-regenerated.patch have been tested end-to-end with Electrum on my laptop + I can get feedback from other Fedora users before it is moved from the testing to stable repo.

**Comment by prusnak** [comment]
In branch **0.7.x**:
1) regenerated proto files using `protobuf-2.6.1`
2) set requirement to `protobuf==2.6.1`

So no patches should be needed in Fedora-25 downstream if branch 0.7.x is used

For distros shipping protobuf-3.x I recommend packaging master.

**Comment by prusnak** [comment]
I just noticed that build for 0.7.x branch fails on Python3, because protobuf 2.6.1 is not Python3 compatible :-/ Ah, well ...

**Comment by hegjon** [comment]
> So no patches should be needed in Fedora-25 downstream if branch 0.7.x is used

Great, thanks. I will use 0.7.x for Fedora 25 and the next release from master on Fedora 26 and later.

**Pull request closed without merging**
