### PR TITLE
Remove default curve

### PR DESCRIPTION
**Pull request by saleemrashid**
Bitten by this when testing Decred.

### CODE REVIEW

**Comment by prusnak** [comment]
@romanz Could you please confirm this is OK for your usage in https://github.com/romanz/trezor-agent ?

**Comment by saleemrashid** [comment]
AFAICT it should be fine because https://github.com/romanz/trezor-agent doesn't reference `trezorlib.client.DEFAULT_CURVE`. This doesn't actually change behaviour for coins that use `secp256k1` (the device will select `secp256k1`). This only changes behaviour for coins such as Decred, which uses `secp256k1_decred`.

**Comment by prusnak** [comment]
I checked that trezor-agent indeed does not call the patched 3 methods with unset ecdsa_curve_name parameter.

**Comment by saleemrashid** [comment]
@prusnak Even if it did, it would not be a problem as the device would default to `secp256k1` (which is what `DEFAULT_CURVE` was set to)

**Comment by romanz** [comment]
Looks good, thanks for the fix :)

**Pull request merged**
