### PR TITLE
Add support for get_ethereum_address to trezorlib and trezorctl

### PR DESCRIPTION
**Pull request by Arachnid**

### CODE REVIEW

**Comment by prusnak** [comment]
Please rename get_ethereum_address to ethereum_get_address. Otherwise it seems fine.

**Comment by prusnak** [comment]
Also don't use `address.encode('hex')` but `binascii.hexlify(address)`. The former does not work with python3.

**Comment by Arachnid** [comment]
Do you want me to rename the trezorctl command too? `ethereum_get_address` seems rather less intuitive for users to call.

**Comment by prusnak** [comment]
Yes, please. Trezorctl is used by developers not users, anyway. And it
makes sense that commands follow message name. We might come with a
different invocation mechanism in the futur, e.g I can imagine calling:
 
trezorctl management wipe_device
trezorctl bitcoin get_address
trezorctl ethereum get_address
 
Where the first param is the "app" or module name.
 
--
Best Regards / S pozdravom,
 
Pavol Rusnak <stick@gk2.sk>
 
 
On Wed, May 25, 2016, at 11:51 AM, Nick Johnson wrote:
> Do you want me to rename the trezorctl command too?
> ethereum_get_address seems rather less intuitive for users to call.
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/trezor/python-trezor/pull/60#issuecomment-221526132

**Comment by Arachnid** [comment]
PTAL!

**Comment by prusnak** [comment]
LGTM. Thanks!

**Pull request merged**
