### PR TITLE
Add Groestlcoin support

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**
This PR depends on https://github.com/trezor/trezor-common/pull/91 and https://github.com/trezor/trezor-crypto/pull/148

### CODE REVIEW

**Comment by gruve-p** [comment]
Tested on emulator with Electrum-GRS (https://github.com/Groestlcoin/electrum-grs/tree/merge-3-1-2)
Works like a charm! Ack

**Comment by Yokomoko** [comment]
Reviewed and tested against electrum 3.1.2. ACK

**Comment by duudl3** [comment]
Working well on Electrum-GRS (3.1.2). Ack

**Comment by Cold-A-Muse** [comment]
ACK, tested with electrum-grs 3.1.2 and seems to be working fine

**Comment by joenilan** [comment]
ACK. All good my end

**Comment by HAMMERjah** [comment]
ACK

**Comment by prusnak** [comment]
After https://github.com/trezor/python-trezor/commit/bd43363b1cbc3d966a9b30747a17f1616c00316e merged, coins now use generated definitions from coins.json, so a commit to trezor-common to include the coin definition is enough. Closing.

**Comment by gruve-p** [comment]
Thanks for the clarification @prusnak

**Pull request closed without merging**
