### PR TITLE
Steem integration

### PR DESCRIPTION
**Pull request by xeroc**
Basic support to help test the Steem integration and manually sign transaction using `TrezorClient` python library.

`trezorctl` can be used to interact with the Trezor using Steem with:

```
python2 trezorctl steem_transfer -bn 21671 -bp 313383925 -ex '2016-09-29T15:50:28' -f fabian -t xeroc -am 15.1 -as "SBD" -m ""
```
- `-bn` is the block number (TaPOS parameter for consensus)
- `-bp` is the block prefix (TaPOS parameter for consensus)
- `-ex` is the expiration time for the transaction
- the other parameters are for _from_, _to_, _amount_, _asset_, and _memo_ (not presented on the Trezor screen yet)

The signature returned by the trezor can be validated using `python-steem` library (python3):

``` python
from pprint import pprint
from steembase.account import PublicKey
from steembase.signedtransactions import Signed_Transaction
import sys
from binascii import hexlify, unhexlify

tx = eval(sys.stdin.read())
pprint(tx)
print("="*80)

tx2 = Signed_Transaction(**tx)
tx2.deriveDigest("STEEM")
print(hexlify(tx2.digest))

assert hexlify(tx2.digest).decode("ascii") == tx["digest"], "Digests don't match"

print(tx2._is_canonical(unhexlify(tx["signatures"][0])))
print(hexlify(bytes(tx2)))

print("="*80)

for k in tx2.verify():
    k = PublicKey(k)
    print(format(k, "STM"))
    k = PublicKey(k.compressed())
    print(format(k, "STM"))
```

### CODE REVIEW

**Comment by slush0** [comment]
Thanks! I'll review & merge it when Steem code gets accepted to -mcu.

**Comment by xeroc** [comment]
Latest commit adds an operation to update an account .. read [slip-48](https://github.com/satoshilabs/slips/issues/49) to understand the reasons for this operation!

**Comment by matejcik** [comment]
This PR is now hopelessly out of date, and AFAICT there are no efforts on either of the devices.

Also, new protobuf messages must be added through `trezor-common` repository. If you wish to continue to work on Steem, send a PR to trezor-common first.

**Comment by prusnak** [comment]
This is my fault actually, PR to trezor-common is here: https://github.com/trezor/trezor-common/pull/19

**Pull request closed without merging**
