### PR TITLE
Add pass_client decorator to trezorctl

### PR DESCRIPTION
**Pull request by saleemrashid**
This replaces the `connect` function for instantiating the client with a decorator.

/cc @jpochyla

### CODE REVIEW

**Comment by matejcik** [comment]
The code has drifted too far in the meantime :/ I thought that the main cause of conflict was #226, where I rewrote the code for path matching. But there's actually a lot more conflicts.
Would you care to fix them?

**Comment by matejcik** [comment]
...actually, reading it again, I was under the impression that the reason for having `connect()` work this way is so that the connection is deferred until after _some code_ runs. Most likely instance of "some code" is the firmware download in `firmware_update()`, and possibly also the checks in `set_homescreen()`.
Otherwise you could just assign the client directly to `ctx.obj` and be done with it, no need for a custom decorator.
But your PR loses this anyway, so I'm not sure if this is a good way to do things.

Thoughts?
Maybe leave `cli()` as is, have the decorator only call `connect()`, and use it everywhere except the firmware and homescreen functions?
(I'm not convinced that it's worth it though...)

**Comment by saleemrashid** [comment]
>  Otherwise you could just assign the client directly to `ctx.obj` and be done with it, no need for a custom decorator.

I believed the issue was that this would attempt to connect to the device, even for `--help` (see #123)

**Comment by matejcik** [comment]
hmm, yes, it makes sense in that case.

please fix the conflicts and i'll merge this.

**Comment by matejcik** [comment]
i'm going to close this PR. please reopen if you ever have the time to fix the conflicts

**Pull request closed without merging**
