### PR TITLE
Restore Lisk sign and verify message functionality

### PR DESCRIPTION
**Pull request by alepop**
Restore methods for signing and verifying message with updated tests.

### CODE REVIEW

**Comment by matejcik** [comment]
jfyi this won't pass CI checks (and we won't merge it) until `trezor-common` is updated with the protobuf messages

**Comment by matejcik** [comment]
corresponding trezor-common PR: https://github.com/trezor/trezor-common/pull/120

**Comment by prusnak** [comment]
https://github.com/trezor/trezor-common/pull/120 is merged now 

I changed the order of fields in LiskVerifyMessage (https://github.com/trezor/trezor-common/commit/babc60a48ec95df8de0ddd11b9d7e24b0e7e1d46) so this message needs to be regenerated.

**Comment by matejcik** [comment]
merged via e110d874949961b9980d73cd9468e052b26573ba

**Pull request closed without merging**
