### PR TITLE
Readme: Click is necessary for latest master

### PR DESCRIPTION
**Pull request by runn1ng**

### CODE REVIEW

**Comment by saleemrashid** [comment]
@runn1ng This should be installed by `pip` anyway

**Comment by prusnak** [comment]
Yeah, like Saleem says.

**Comment by prusnak** [comment]
Version published to PyPI (0.7.x) does not require click.

Master requires click, but it is also listed as a dependency, thus 

```
pip install git+https://github.com/trezor/python-trezor@master
```

Should install click as well.

**Comment by runn1ng** [comment]
Oh you are right. OK

**Pull request closed without merging**
