### PR TITLE
Allow setting auto-lock delay

### PR DESCRIPTION
**Pull request by romanz**
This PR depends on https://github.com/trezor/trezor-common/pull/87 and https://github.com/trezor/trezor-mcu/pull/315.

### CODE REVIEW

**Comment by romanz** [comment]
@prusnak Should I add a simple test here?
https://github.com/trezor/python-trezor/blob/master/trezorlib/tests/device_tests/test_msg_applysettings.py

**Comment by matejcik** [comment]
@romanz yes, please add the test

**Comment by matejcik** [comment]
Hmm, that's a rather long delay.
OTOH i suppose the minimum delay is there for a reason. Perhaps the test should also check that you cannot set a lower value.
Then maybe we can mark the delay test somehow so that it can be easily skipped?

**Comment by prusnak** [comment]
I changed the minimum delay to 10 seconds in https://github.com/trezor/trezor-mcu/commit/783f1c0323013244a442778ae9b3cbec4e449a5b

You can rework the test to use the new value and I agree with @matejcik that we can add another test that setting to e.g. 5 seconds does not work (and still at least 10 seconds are used).

**Comment by romanz** [comment]
Sounds good, I've updated and pushed a new commit.

**Comment by matejcik** [comment]
looks mostly good now.
one last thing, given that minimum is 10s, maybe the trezorctl command should take seconds instead of minutes? (or even "60" / "60s" / "1m")

**Comment by matejcik** [comment]
ummm no, let's not add a dependency for this!

I was thinking of something like:
```python
if delay[-1] == "m":
  seconds = 60 * int(delay[:-1])
elif delay[-1] == "s":
  seconds = int(delay[:-1])
else:
  seconds = int(delay)
```

(Sorry for being so nitpicky. But this feature is simply not important enough to warrant a new dependency, however small. I'd also be OK with just switching from minutes to seconds, without any suffix logic whatsoever.)

**Comment by romanz** [comment]
No problem :)
Updated the PR.

**Comment by matejcik** [comment]
perfect, thank you :)

**Comment by prusnak** [comment]
Thank you Roman! Your contributions are very much welcome!

**Comment by romanz** [comment]
Happy to help :)

**Pull request merged**
