### PR TITLE
fix v1 protocol

### PR DESCRIPTION
**Pull request by mruddy**
small patch to get things working again.
test with: trezorctl get_features

### CODE REVIEW

**Comment by saleemrashid** [comment]
@mruddy Have you tested that on both Python versions? I suspect that will break whichever one you are not using

**Comment by mruddy** [comment]
@saleemrashid Yes, I got it working on python2 at least since when running with python3, there were further problems.

**Comment by prusnak** [comment]
I think the correct fix is '`b\x00'`

**Comment by mruddy** [comment]
@prusnak updated, thanks

**Comment by mruddy** [comment]
btw, the further problem that i hit with python3 was due to the hid package:
```
hid/__init__.py, line 79
print 'opening with path'

SyntaxError: Missing parentheses in call to 'print'
```

**Comment by prusnak** [comment]
@jpochyla will look at it tomorrow as he is the one who broke it! :-)

**Pull request merged**
