### PR TITLE
Added code to make trezor-agent work with keepkey.

### PR DESCRIPTION
**Pull request by bgok**
Would you be interested in taking this pull request? It is needed to make Roman's trezor-agent work for keepkey with minimal changes.

Thanks.

### CODE REVIEW

**Comment by prusnak** [comment]
Thanks!

**Comment by dstanchfield** [comment]
Anyway we can get this support for KeepKey removed.  This will cause problems with our electrum plugin.

**Comment by prusnak** [comment]
Reverted in 8b7e6058ed8c55bd462c26037c21a73af90d6d86.

**Comment by dstanchfield** [comment]
Thanks!

**Comment by kyuupichan** [comment]
Hmm, maybe I should hard-code the device IDs in Electrum and not import them from the library headers?

**Comment by prusnak** [comment]
Best would be, of course, to create one plugin that would handle both devices. Keepkey's code is just same as TREZOR code with replaced strings anyway.

**Comment by kyuupichan** [comment]
It's not the same actually.

There plugin code is 99% shared in Electrum.

Now if you two could agree on a common single library, that would be the most helpful.  I could then indeed eliminate the plugin separation in Electrum, but not until then.

**Pull request merged**
