### PR TITLE
USAGE: Adding more examples

### PR DESCRIPTION
**Pull request by jonathancross**

### CODE REVIEW

**Comment by jonathancross** [comment]
I'd like to add more examples, but have had issues with the following:
1. How do I retrieve the bitcoin xpub to be used in a watch-only wallet?  `trezorctl get_public_node -c Bitcoin -n "m/44'/0'/0'/0/0"` produces and `xpub`, but it is different from wallet.trezor.io -- Is there something else needed?
2. In this command `trezorctl get_address -c Bitcoin -t segwit`, what does "script-type" "segwit" actually mean? Bech32? (see also #144)
3. Is Bitcoin transaction signing working? `sign_tx` is not shown in `--help`:
```
Available commands:
  {backup_device,change_pin,clear_session,decrypt_keyvalue,decrypt_message,disable_passphrase,enable_passphrase,encrypt_keyvalue,encrypt_message,ethereum_get_address,ethereum_sign_tx,firmware_update,get_address,get_entropy,get_features,get_public_node,list,list_coins,load_device,ping,recovery_device,reset_device,self_test,set_homescreen,set_label,set_u2f_counter,sign_message,verify_message,wipe_device}
    backup_device       Perform device seed backup
    change_pin          Change new PIN or remove existing
    clear_session       Clear session (remove cached PIN, passphrase, etc.)
    decrypt_keyvalue    Decrypt value by given key and path
    decrypt_message     Decrypt message
    disable_passphrase  Disable passphrase
    enable_passphrase   Enable passphrase
    encrypt_keyvalue    Encrypt value by given key and path
    encrypt_message     Encrypt message
    ethereum_get_address
                        Get Ethereum address in hex encoding
    ethereum_sign_tx    Sign (and optionally publish) Ethereum transaction
    firmware_update     Upload new firmware to device (must be in bootloader
                        mode)
    get_address         Get bitcoin address in base58 encoding
    get_entropy         Get example entropy
    get_features        Retrieve device features and settings
    get_public_node     Get public node of given path
    list                List connected TREZOR USB devices
    list_coins          List all supported coin types by the device
    load_device         Load custom configuration to the device
    ping                Send ping message
    recovery_device     Start safe recovery workflow
    reset_device        Perform device setup and generate new seed
    self_test           Perform a self-test
    set_homescreen      Set new homescreen
    set_label           Set new wallet label
    set_u2f_counter     Set U2F counter
    sign_message        Sign message using address of given path
    verify_message      Verify message
    wipe_device         Reset device to factory defaults and remove all
                        private data.
```

**Comment by jonathancross** [comment]
I'd like to add more examples, but have had issues with the following:
1. How do I retrieve the bitcoin xpub to be used in a watch-only wallet?  `trezorctl get_public_node -c Bitcoin -n "m/44'/0'/0'/0/0"` produces and `xpub`, but it is different from wallet.trezor.io -- Is there something else needed?
2. In this command `trezorctl get_address -c Bitcoin -t segwit`, what does "script-type" "segwit" actually mean? Bech32? (see also #144)
3. Is Bitcoin transaction signing working? `sign_tx` is not shown in `--help`:
```
Available commands:
  {backup_device,change_pin,clear_session,decrypt_keyvalue,decrypt_message,disable_passphrase,enable_passphrase,encrypt_keyvalue,encrypt_message,ethereum_get_address,ethereum_sign_tx,firmware_update,get_address,get_entropy,get_features,get_public_node,list,list_coins,load_device,ping,recovery_device,reset_device,self_test,set_homescreen,set_label,set_u2f_counter,sign_message,verify_message,wipe_device}
    backup_device       Perform device seed backup
    change_pin          Change new PIN or remove existing
    clear_session       Clear session (remove cached PIN, passphrase, etc.)
    decrypt_keyvalue    Decrypt value by given key and path
    decrypt_message     Decrypt message
    disable_passphrase  Disable passphrase
    enable_passphrase   Enable passphrase
    encrypt_keyvalue    Encrypt value by given key and path
    encrypt_message     Encrypt message
    ethereum_get_address
                        Get Ethereum address in hex encoding
    ethereum_sign_tx    Sign (and optionally publish) Ethereum transaction
    firmware_update     Upload new firmware to device (must be in bootloader
                        mode)
    get_address         Get bitcoin address in base58 encoding
    get_entropy         Get example entropy
    get_features        Retrieve device features and settings
    get_public_node     Get public node of given path
    list                List connected TREZOR USB devices
    list_coins          List all supported coin types by the device
    load_device         Load custom configuration to the device
    ping                Send ping message
    recovery_device     Start safe recovery workflow
    reset_device        Perform device setup and generate new seed
    self_test           Perform a self-test
    set_homescreen      Set new homescreen
    set_label           Set new wallet label
    set_u2f_counter     Set U2F counter
    sign_message        Sign message using address of given path
    verify_message      Verify message
    wipe_device         Reset device to factory defaults and remove all
                        private data.
```

**Comment by jonathancross** [comment]
I'd like to add more examples, but have had issues with the following:
1. How do I retrieve the bitcoin xpub to be used in a watch-only wallet?  `trezorctl get_public_node -c Bitcoin -n "m/44'/0'/0'/0/0"` produces and `xpub`, but it is different from wallet.trezor.io -- Is there something else needed?
2. In this command `trezorctl get_address -c Bitcoin -t segwit`, what does "script-type" "segwit" actually mean? Bech32? (see also #144)
3. Is Bitcoin transaction signing working? `sign_tx` is not shown in `--help`:
```
Available commands:
  {backup_device,change_pin,clear_session,decrypt_keyvalue,decrypt_message,disable_passphrase,enable_passphrase,encrypt_keyvalue,encrypt_message,ethereum_get_address,ethereum_sign_tx,firmware_update,get_address,get_entropy,get_features,get_public_node,list,list_coins,load_device,ping,recovery_device,reset_device,self_test,set_homescreen,set_label,set_u2f_counter,sign_message,verify_message,wipe_device}
    backup_device       Perform device seed backup
    change_pin          Change new PIN or remove existing
    clear_session       Clear session (remove cached PIN, passphrase, etc.)
    decrypt_keyvalue    Decrypt value by given key and path
    decrypt_message     Decrypt message
    disable_passphrase  Disable passphrase
    enable_passphrase   Enable passphrase
    encrypt_keyvalue    Encrypt value by given key and path
    encrypt_message     Encrypt message
    ethereum_get_address
                        Get Ethereum address in hex encoding
    ethereum_sign_tx    Sign (and optionally publish) Ethereum transaction
    firmware_update     Upload new firmware to device (must be in bootloader
                        mode)
    get_address         Get bitcoin address in base58 encoding
    get_entropy         Get example entropy
    get_features        Retrieve device features and settings
    get_public_node     Get public node of given path
    list                List connected TREZOR USB devices
    list_coins          List all supported coin types by the device
    load_device         Load custom configuration to the device
    ping                Send ping message
    recovery_device     Start safe recovery workflow
    reset_device        Perform device setup and generate new seed
    self_test           Perform a self-test
    set_homescreen      Set new homescreen
    set_label           Set new wallet label
    set_u2f_counter     Set U2F counter
    sign_message        Sign message using address of given path
    verify_message      Verify message
    wipe_device         Reset device to factory defaults and remove all
                        private data.
```

**Comment by prusnak** [comment]
1. "m/44'/0'/0'/0/0" is address node, if you want account node use path "m/44'/0'/0'" for 1st account

2. yes, segwit is native segwit (bech32), which is not implemented yet in the firmware, but will be in future version

3. yes, let's discuss in #146

**Pull request merged**
